config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'frontend#home'
  get 'about', to: 'frontend#about'
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 1, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = 'Article was created'
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def update
    @article = Article.find params[:id]
    if @article.update(article_params)
      flash[:notice] = 'Article was updated'
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def home

  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<% if  @article.errors.any? %>
    <h4>Invalid entries</h4>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for @article do |form|%>
    <p>
      <%= form.label :title %> </br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :description %> </br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.submit %>
    </p>
    <p><%= link_to 'All Articles', articles_path%></p>
<% end %>

app/views/articles/index.html.erb
<h1>Index</h1>

<p>
  <%= link_to 'Create Article', new_article_path %>
</p>

<table>
  <tr>
    <th>
      Title
    </th>
    <th>
      Description
    </th>
  </tr>

  <% @article.each do |article| %>

  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td>

    </td>
  </tr>
      <% end %>
</table>

app/views/articles/new.html.erb
<h2>TEST</h2>

<% if  @article.errors.any? %>
    <h4>Invalid entries</h4>
 <ul>
   <% @article.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
 </ul>
<% end %>

<%= form_for @article do |form|%>
  <p>
    <%= form.label :title %> </br>
    <%= form.text_field :title %>
  </p>
    <p>
      <%= form.label :description %> </br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1>Show selected article</h1>

<p> Title: <%= @article.title %></p>
<p> Description: <%= @article.description %></p>
<p><%= link_to 'All Articles', articles_path%> <%= link_to 'Edit', edit_article_path(@article) %></p>

app/views/frontend/about.html.erb
<h1>Test About</h1>

<%= link_to 'Home', root_path %>

app/views/frontend/home.html.erb
<h1>Test Home</h1>

<%= link_to 'About', about_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
  <ul>
      <li><%= msg %></li>
  </ul>
  <% end %>
    <%= yield %>
  </body>
</html>